### ISSUE TITLE
赞！不过是否应该标注清楚参考资料🤔

### ISSUE THREAD

**Issue by rookielzy** [sudongyuer/javascript-mental-models#3]
https://justjavascript.com/ by Dan Abramov

有幸读过 Dan Abramov 的文章，同样你的总结归纳也非常棒！

**Comment by sudongyuer** [comment]
> https://justjavascript.com/ by Dan Abramov
> 
> 有幸读过 Dan Abramov 的文章，同样你的总结归纳也非常棒！

收到 这就标明资料
