### ISSUE TITLE
函数在 js 里面不是一种基本类型

### ISSUE THREAD

**Issue by yyzclyang** [sudongyuer/javascript-mental-models#6]
第二章那里说错了，函数不是基本类型，函数是一个对象

参考 [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#normal_objects_and_functions)

**Comment by sudongyuer** [comment]
> 第二章那里说错了，函数不是基本类型，函数是一个对象
> 
> 参考 [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#normal_objects_and_functions)

没看见哪里写错 请指出第几段 或者PR 函数确实不属于基本类型这没错

**Comment by yyzclyang** [comment]
> > 第二章那里说错了，函数不是基本类型，函数是一个对象
> 
> > 
> 
> > 参考 [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#normal_objects_and_functions)
> 
> 
> 
> 没看见哪里写错 请指出第几段 或者PR 函数确实不属于基本类型这没错


Types of Values 那节，你说 JavaScript 有9种类型，是把函数和对象当作了两种类型，但是函数的类型是对象，它不是一个单独的类型

**Comment by sudongyuer** [comment]
函数和对象是两种值类型 函数是特殊的对象
